# Generated by Django 2.1.9 on 2020-01-16 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('apis_relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventevent',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='eventpassage',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='eventpublication',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='institutionevent',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='institutioninstitution',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='institutionpassage',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='institutionplace',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='institutionpublication',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='passagepassage',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='passagepublication',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='personevent',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='personinstitution',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='personpassage',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='personperson',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='personplace',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='personpublication',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='placeevent',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='placepassage',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='placeplace',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='placepublication',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='publicationpublication',
            managers=[
                ('annotation_links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='eventevent',
            name='related_eventA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_eventB', to='apis_entities.Event'),
        ),
        migrations.AlterField(
            model_name='eventevent',
            name='related_eventB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_eventA', to='apis_entities.Event'),
        ),
        migrations.AlterField(
            model_name='eventevent',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventevent_set', to='apis_vocabularies.EventEventRelation'),
        ),
        migrations.AlterField(
            model_name='eventpassage',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventpassage_set', to='apis_entities.Event'),
        ),
        migrations.AlterField(
            model_name='eventpassage',
            name='related_passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventpassage_set', to='apis_entities.Passage'),
        ),
        migrations.AlterField(
            model_name='eventpassage',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventpassage_set', to='apis_vocabularies.EventPassageRelation'),
        ),
        migrations.AlterField(
            model_name='eventpublication',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventpublication_set', to='apis_entities.Event'),
        ),
        migrations.AlterField(
            model_name='eventpublication',
            name='related_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventpublication_set', to='apis_entities.Publication'),
        ),
        migrations.AlterField(
            model_name='eventpublication',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventpublication_set', to='apis_vocabularies.EventPublicationRelation'),
        ),
        migrations.AlterField(
            model_name='institutionevent',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionevent_set', to='apis_entities.Event'),
        ),
        migrations.AlterField(
            model_name='institutionevent',
            name='related_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionevent_set', to='apis_entities.Institution'),
        ),
        migrations.AlterField(
            model_name='institutionevent',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionevent_set', to='apis_vocabularies.InstitutionEventRelation'),
        ),
        migrations.AlterField(
            model_name='institutioninstitution',
            name='related_institutionA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_institutionB', to='apis_entities.Institution'),
        ),
        migrations.AlterField(
            model_name='institutioninstitution',
            name='related_institutionB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_institutionA', to='apis_entities.Institution'),
        ),
        migrations.AlterField(
            model_name='institutioninstitution',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutioninstitution_set', to='apis_vocabularies.InstitutionInstitutionRelation'),
        ),
        migrations.AlterField(
            model_name='institutionpassage',
            name='related_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionpassage_set', to='apis_entities.Institution'),
        ),
        migrations.AlterField(
            model_name='institutionpassage',
            name='related_passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionpassage_set', to='apis_entities.Passage'),
        ),
        migrations.AlterField(
            model_name='institutionpassage',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionpassage_set', to='apis_vocabularies.InstitutionPassageRelation'),
        ),
        migrations.AlterField(
            model_name='institutionplace',
            name='related_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionplace_set', to='apis_entities.Institution'),
        ),
        migrations.AlterField(
            model_name='institutionplace',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionplace_set', to='apis_entities.Place'),
        ),
        migrations.AlterField(
            model_name='institutionplace',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionplace_set', to='apis_vocabularies.InstitutionPlaceRelation'),
        ),
        migrations.AlterField(
            model_name='institutionpublication',
            name='related_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionpublication_set', to='apis_entities.Institution'),
        ),
        migrations.AlterField(
            model_name='institutionpublication',
            name='related_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionpublication_set', to='apis_entities.Publication'),
        ),
        migrations.AlterField(
            model_name='institutionpublication',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionpublication_set', to='apis_vocabularies.InstitutionPublicationRelation'),
        ),
        migrations.AlterField(
            model_name='passagepassage',
            name='related_passageA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_passageB', to='apis_entities.Passage'),
        ),
        migrations.AlterField(
            model_name='passagepassage',
            name='related_passageB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_passageA', to='apis_entities.Passage'),
        ),
        migrations.AlterField(
            model_name='passagepassage',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passagepassage_set', to='apis_vocabularies.PassagePassageRelation'),
        ),
        migrations.AlterField(
            model_name='passagepublication',
            name='related_passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passagepublication_set', to='apis_entities.Passage'),
        ),
        migrations.AlterField(
            model_name='passagepublication',
            name='related_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passagepublication_set', to='apis_entities.Publication'),
        ),
        migrations.AlterField(
            model_name='passagepublication',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passagepublication_set', to='apis_vocabularies.PassagePublicationRelation'),
        ),
        migrations.AlterField(
            model_name='personevent',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personevent_set', to='apis_entities.Event'),
        ),
        migrations.AlterField(
            model_name='personevent',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personevent_set', to='apis_entities.Person'),
        ),
        migrations.AlterField(
            model_name='personevent',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personevent_set', to='apis_vocabularies.PersonEventRelation'),
        ),
        migrations.AlterField(
            model_name='personinstitution',
            name='related_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personinstitution_set', to='apis_entities.Institution'),
        ),
        migrations.AlterField(
            model_name='personinstitution',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personinstitution_set', to='apis_entities.Person'),
        ),
        migrations.AlterField(
            model_name='personinstitution',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personinstitution_set', to='apis_vocabularies.PersonInstitutionRelation'),
        ),
        migrations.AlterField(
            model_name='personpassage',
            name='related_passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personpassage_set', to='apis_entities.Passage'),
        ),
        migrations.AlterField(
            model_name='personpassage',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personpassage_set', to='apis_entities.Person'),
        ),
        migrations.AlterField(
            model_name='personpassage',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personpassage_set', to='apis_vocabularies.PersonPassageRelation'),
        ),
        migrations.AlterField(
            model_name='personperson',
            name='related_personA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_personB', to='apis_entities.Person'),
        ),
        migrations.AlterField(
            model_name='personperson',
            name='related_personB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_personA', to='apis_entities.Person'),
        ),
        migrations.AlterField(
            model_name='personperson',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personperson_set', to='apis_vocabularies.PersonPersonRelation'),
        ),
        migrations.AlterField(
            model_name='personplace',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personplace_set', to='apis_entities.Person'),
        ),
        migrations.AlterField(
            model_name='personplace',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personplace_set', to='apis_entities.Place'),
        ),
        migrations.AlterField(
            model_name='personplace',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personplace_set', to='apis_vocabularies.PersonPlaceRelation'),
        ),
        migrations.AlterField(
            model_name='personpublication',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personpublication_set', to='apis_entities.Person'),
        ),
        migrations.AlterField(
            model_name='personpublication',
            name='related_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personpublication_set', to='apis_entities.Publication'),
        ),
        migrations.AlterField(
            model_name='personpublication',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personpublication_set', to='apis_vocabularies.PersonPublicationRelation'),
        ),
        migrations.AlterField(
            model_name='placeevent',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeevent_set', to='apis_entities.Event'),
        ),
        migrations.AlterField(
            model_name='placeevent',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeevent_set', to='apis_entities.Place'),
        ),
        migrations.AlterField(
            model_name='placeevent',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeevent_set', to='apis_vocabularies.PlaceEventRelation'),
        ),
        migrations.AlterField(
            model_name='placepassage',
            name='related_passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placepassage_set', to='apis_entities.Passage'),
        ),
        migrations.AlterField(
            model_name='placepassage',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placepassage_set', to='apis_entities.Place'),
        ),
        migrations.AlterField(
            model_name='placepassage',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placepassage_set', to='apis_vocabularies.PlacePassageRelation'),
        ),
        migrations.AlterField(
            model_name='placeplace',
            name='related_placeA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_placeB', to='apis_entities.Place'),
        ),
        migrations.AlterField(
            model_name='placeplace',
            name='related_placeB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_placeA', to='apis_entities.Place'),
        ),
        migrations.AlterField(
            model_name='placeplace',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeplace_set', to='apis_vocabularies.PlacePlaceRelation'),
        ),
        migrations.AlterField(
            model_name='placepublication',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placepublication_set', to='apis_entities.Place'),
        ),
        migrations.AlterField(
            model_name='placepublication',
            name='related_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placepublication_set', to='apis_entities.Publication'),
        ),
        migrations.AlterField(
            model_name='placepublication',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placepublication_set', to='apis_vocabularies.PlacePublicationRelation'),
        ),
        migrations.AlterField(
            model_name='publicationpublication',
            name='related_publicationA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_publicationB', to='apis_entities.Publication'),
        ),
        migrations.AlterField(
            model_name='publicationpublication',
            name='related_publicationB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_publicationA', to='apis_entities.Publication'),
        ),
        migrations.AlterField(
            model_name='publicationpublication',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicationpublication_set', to='apis_vocabularies.PublicationPublicationRelation'),
        ),
    ]
