# Generated by Django 2.1.9 on 2020-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_relations', '0002_auto_20200116_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagepublication',
            name='bible_book_ref',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='passagepublication',
            name='bible_chapter_ref',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='passagepublication',
            name='bible_verse_ref',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
