# Generated by Django 2.1.9 on 2020-06-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_relations', '0003_auto_20200121_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventevent',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='eventpassage',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='eventpublication',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='institutionevent',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='institutioninstitution',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='institutionpassage',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='institutionplace',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='institutionpublication',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='passagepassage',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='passagepublication',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='personevent',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='personinstitution',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='personpassage',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='personperson',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='personplace',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='personpublication',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='placeevent',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='placepassage',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='placeplace',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='placepublication',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='publicationpublication',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='eventevent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='eventpassage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='eventpublication',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='institutionevent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='institutioninstitution',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='institutionpassage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='institutionplace',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='institutionpublication',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='passagepassage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='passagepublication',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='personevent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='personinstitution',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='personpassage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='personperson',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='personplace',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='personpublication',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='placeevent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='placepassage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='placeplace',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='placepublication',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='publicationpublication',
            managers=[
            ],
        ),
    ]
