# Generated by Django 2.2.11 on 2021-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_relations', '0004_auto_20200626_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagepublication',
            name='bible_ref_label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='passagepublication',
            name='bible_ref_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
