# Generated by Django 2.2.11 on 2021-11-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_relations', '0005_auto_20210531_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagepublication',
            name='bible_book_ref',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='passagepublication',
            name='bible_chapter_ref',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='passagepublication',
            name='bible_verse_ref',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
