trigger_build:
  only:
     refs:
         - master
         - jwv
         - coladay
  stage: deploy
  trigger: acdh-oeaw/apis/apis-docker
  variables:
      APIS_TRIGGERD_BY: 'apis-core'
      APIS_VERSION: '0.9'
