workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /-doc$/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  HTTP_PROXY: http://fifi:8080/
  HTTPS_PROXY: http://fifi:8080/
  NO_PROXY: "docker:2375,docker:2376"
 
stages:
  - test
  - build
  - deploy
image:
  name: python:3.8

before_script:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry config pypi-token.pypi ${PYPI_TOKEN}
  - poetry update
  - poetry install

test:
  stage: test
  only:
    refs:
      - master
      - coladay
      - jwv
  services:
    - mariadb:latest
  variables:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: apisdb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
  script:
    - export DATABASE_URL=mysql://root:$MYSQL_ROOT_PASSWORD@mariadb:3306/$MYSQL_DATABASE
    - poetry run python manage.py migrate
    - poetry run python manage.py test
build:
  only:
      refs:
        - pipelines
        - triggers
        - master

  stage: build
  tags:
    - cluster
  script:
    - poetry run bash checkandbump.sh
    - poetry publish --build

trigger_build:
  only:
     refs:
         - master
         - jwv
         - coladay
  stage: deploy
  trigger: acdh-oeaw/apis/apis-docker
  variables:
      APIS_TRIGGERD_BY: 'apis-core'
      APIS_VERSION: '0.9'
