# Generated by Django 2.1.9 on 2019-06-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profession',
        ),
    ]
