# Generated by Django 2.1.2 on 2019-07-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0002_remove_person_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name_english',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_english',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='name_english',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
