# Generated by Django 2.1.9 on 2020-01-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0004_auto_20191115_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='topics',
            field=models.ManyToManyField(blank=True, to='apis_vocabularies.PassageTopics'),
        ),
    ]
