# Generated by Django 2.1.9 on 2020-03-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0007_auto_20200304_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='kind',
        ),
    ]
