# Generated by Django 2.1.9 on 2020-03-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0008_auto_20200304_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passage',
            old_name='kind_new',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='kind_new',
            new_name='kind',
        ),
    ]
