# Generated by Django 2.1.9 on 2020-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0009_auto_20200304_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='kind',
            field=models.ManyToManyField(blank=True, to='apis_vocabularies.PassageType'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='kind',
            field=models.ManyToManyField(blank=True, to='apis_vocabularies.PassageType'),
        ),
    ]
