# Generated by Django 2.1.9 on 2020-09-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0012_auto_20200820_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passage',
            old_name='topics',
            new_name='topic',
        ),
    ]
