# Generated by Django 2.1.9 on 2020-10-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0013_auto_20200902_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
    ]
