# Generated by Django 2.1.9 on 2020-10-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0014_remove_person_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='title',
        ),
    ]
