Place:
  data:
    - base_url: https://sws.geonames.org/
      attributes:
        - name: name
          sparql: |
            SELECT ?prefName (LANG(?prefName) AS ?lang)
            WHERE {
            {
              ?subject gn:name ?prefName}
              UNION {
                ?subject gn:officialName ?prefName
              } 
              UNION {
                ?subject gn:alternateName ?prefName
              }
              FILTER (LANGMATCHES(LANG(?prefName), "de") || LANGMATCHES(LANG(?prefName), "en") || LANG(?prefName) = "")
                  }
            ORDER BY ?lang
        - name: altName
          sparql: |
            PREFIX gn: <http://www.geonames.org/ontology#>
            SELECT ?altName (LANG(?altName) AS ?lang)
            WHERE {
              ?subject gn:alternateName ?altName
              FILTER (LANGMATCHES(LANG(?altName), "de") || LANGMATCHES(LANG(?altName), "en") || LANG(?prefName) = "")
                  }
        - name: kind
          sparql: |
            PREFIX gn: <http://www.geonames.org/ontology#>
            SELECT ?kind
            WHERE {
              ?subject gn:featureCode ?kind
                  }
        - name: lat-long
          sparql: |
            PREFIX gn: <http://www.geonames.org/ontology#>
            PREFIX wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
            SELECT ?lat ?long
              WHERE {
                ?subject wgs84_pos:lat ?lat;
                wgs84_pos:long ?long
                    }
        - name: parent
          sparql: |
            PREFIX gn: <http://www.geonames.org/ontology#>
            SELECT ?parent
              WHERE {
                ?subject gn:parentCountry ?parent
                    }
    - base_url: d-nb.info
      attributes:
        - name: name
          sparql: |
            PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
            SELECT ?prefName
              WHERE {
                ?subject gndo:preferredNameForThePlaceOrGeographicName ?prefName
                }
        - name: lat-long-gnd
          sparql: |
            PREFIX geo: <http://www.opengis.net/ont/geosparql#>
            SELECT ?point
              WHERE {
                ?subject geo:hasGeometry ?geo1 .
                ?geo1 geo:asWKT ?point
                }
  matching:
    attributes:
      name:
        string: '{prefName}'
      kind:
        domain: geonames.org
        string: '{kind}'
        accessor: name
        regex: null
      lat:
        domain: geonames.org
        identifier: lat-long.lat
        data type: float
      lng:
        domain: geonames.org
        identifier: lat-long.long
        data type: float
      lng-gnd:
        domain: d-nb.info
        identifier: lat-long-gnd.point
        field name: lng
        data type: float
        regex:
          - '([\-0-9\.]+)'
          - 1
      lat-gnd:
        domain: d-nb.info
        identifier: lat-long-gnd.point
        field name: lat
        data type: float
        regex:
          - \d\s\+([\-0-9\.]+)
          - 1

    labels:
      - label type: alternative name
        identifier: altName
    linked objects:
      - type: Place
        kind: located in
        identifier: parent
Person:
  data:
    - base_url: d-nb.info
      attributes:
        - name: name
          sparql: |
            PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>

            SELECT ?name ?first_name

            WHERE {
              ?subject gndo:preferredNameForThePerson ?name .
              OPTIONAL {
              ?subject gndo:preferredNameEntityForThePerson ?med .
              ?med gndo:forename ?first_name;
                    gndo:surname ?name2 .
                BIND(?name2 as ?name)
            }
            }
        - name: profession
          sparql: |
            PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>

            SELECT ?profession

            WHERE {
              ?subject gndo:professionOrOccupation ?profession
            }
        - name: start_date_written
          sparql: |
            PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>

            SELECT ?start_date_written

            WHERE {
              ?subject gndo:dateOfBirth ?start_date_written
            }
        - name: end_date_written
          sparql: |
            PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>

            SELECT ?end_date_written

            WHERE {
              ?subject gndo:dateOfDeath ?end_date_written
            }
        - name: place_of_birth
          sparql: |
            PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>

            SELECT ?place_of_birth

            WHERE {
              ?subject gndo:placeOfBirth ?place_of_birth
            }
  matching:
    prefLabels:
      - https://d-nb.info/standards/elementset/gnd#preferredNameForTheSubjectHeading
    attributes:
      name:
        string: '{name}'
      first_name:
        identifier: name
        string: '{first_name}'
      start_date_written:
        string: '{start_date_written}'
      end_date_written:
        string: '{end_date_written}'
      profession:
        string: '{profession}'
        accessor: name
        linked: true
    linked objects:
      - type: Place
        kind: Place of Birth
        identifier: place_of_birth
Institution:
  data:
    - base_url: d-nb.info
      attributes:
        - name: name
          sparql: |
            PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
            SELECT ?name
              WHERE {
                ?subject gndo:preferredNameForTheCorporateBody ?name
                }
        - name: altName
          sparql: |
            PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
            SELECT ?altName
              WHERE {
                ?subject gndo:variantNameForTheCorporateBody ?altName
                }
        - name: place
          sparql: |
            PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
            SELECT ?place
              WHERE {
                ?subject gndo:placeOfBusiness ?place
                }
        - name: start_date_written
          sparql: |
            PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
            SELECT ?start_date_written
              WHERE {
                ?subject gndo:dateOfEstablishment ?start_date_written
                }
        - name: end_date_written
          sparql: |
            PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
            SELECT ?end_date_written
              WHERE {
                ?subject gndo:dateOfTermination ?end_date_written
                }
  matching:
    attributes:
      name:
        string: '{name}'
      start_date_written:
        string: '{start_date_written}'
      end_date_written:
        string: '{end_date_written}'
    linked objects:
      - type: Place
        kind: located in
        identifier: place.place
    labels:
      - label type: alternative name
        identifier: altName