# Generated by Django 2.1.2 on 2019-07-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0003_auto_20190614_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempentityclass',
            name='end_date_is_exact',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempentityclass',
            name='start_date_is_exact',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
