# Generated by Django 2.1.9 on 2020-02-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0004_auto_20190702_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempentityclass',
            name='end_date_is_exact',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='tempentityclass',
            name='start_date_is_exact',
            field=models.NullBooleanField(),
        ),
    ]
