# Generated by Django 2.1.9 on 2020-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0005_auto_20200204_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tempentityclass',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='text',
            name='lang',
            field=models.CharField(blank=True, default='deu', help_text="The ISO 639-3 (or 2) code for the label's language.", max_length=3, null=True, verbose_name='ISO Code'),
        ),
    ]
