# Generated by Django 2.1.9 on 2020-07-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0006_auto_20200626_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='lang',
        ),
    ]
