# Generated by Django 2.1.9 on 2020-10-13 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis_metainfo', '0008_tempentityclass_primary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempentityclass',
            name='zustaendig_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Zuständiger User'),
        ),
    ]
