# Generated by Django 2.1.9 on 2020-10-13 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0009_tempentityclass_zustaendig_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempentityclass',
            old_name='zustaendig_user',
            new_name='assigned_user',
        ),
    ]
