# Generated by Django 2.1.2 on 2019-07-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabsbaseclass',
            name='name_english',
            field=models.CharField(max_length=255, null=True, verbose_name='Name (EN)'),
        ),
    ]
