# Generated by Django 2.1.2 on 2019-07-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_vocabularies', '0002_vocabsbaseclass_name_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationbaseclass',
            name='name_reverse_english',
            field=models.CharField(blank=True, help_text='Inverse relation like: "is sub-class of" vs. "is super-class of".', max_length=255, verbose_name='Name reverse (EN)'),
        ),
    ]
