# Generated by Django 2.1.9 on 2019-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0004_auto_20191115_1224'),
        ('apis_relations', '0001_initial'),
        ('apis_vocabularies', '0003_relationbaseclass_name_reverse_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventeventrelation',
            name='eventB_set',
            field=models.ManyToManyField(blank=True, related_name='eventA_relationtype_set', through='apis_relations.EventEvent', to='apis_entities.Event'),
        ),
        migrations.AddField(
            model_name='institutioninstitutionrelation',
            name='institutionB_set',
            field=models.ManyToManyField(blank=True, related_name='institutionA_relationtype_set', through='apis_relations.InstitutionInstitution', to='apis_entities.Institution'),
        ),
        migrations.AddField(
            model_name='passagepassagerelation',
            name='passageB_set',
            field=models.ManyToManyField(blank=True, related_name='passageA_relationtype_set', through='apis_relations.PassagePassage', to='apis_entities.Passage'),
        ),
        migrations.AddField(
            model_name='personpersonrelation',
            name='personB_set',
            field=models.ManyToManyField(blank=True, related_name='personA_relationtype_set', through='apis_relations.PersonPerson', to='apis_entities.Person'),
        ),
        migrations.AddField(
            model_name='placeplacerelation',
            name='placeB_set',
            field=models.ManyToManyField(blank=True, related_name='placeA_relationtype_set', through='apis_relations.PlacePlace', to='apis_entities.Place'),
        ),
        migrations.AddField(
            model_name='publicationpublicationrelation',
            name='publicationB_set',
            field=models.ManyToManyField(blank=True, related_name='publicationA_relationtype_set', through='apis_relations.PublicationPublication', to='apis_entities.Publication'),
        ),
    ]
