# Generated by Django 2.1.9 on 2020-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_vocabularies', '0004_auto_20191115_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttype',
            name='lang',
            field=models.CharField(blank=True, default='deu', help_text="The ISO 639-3 (or 2) code for the label's language.", max_length=3, null=True, verbose_name='ISO Code'),
        ),
    ]
