# Generated by Django 2.1.9 on 2020-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_vocabularies', '0005_texttype_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='professiontype',
            name='temporary_field_for_workaround',
            field=models.CharField(default='x', max_length=3),
        ),
    ]
