# Generated by Django 2.1.9 on 2020-08-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_vocabularies', '0005_texttype_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professiontype',
            name='vocabsbaseclass_ptr',
        ),
        migrations.DeleteModel(
            name='ProfessionType',
        ),
    ]
