# Generated by Django 2.1.9 on 2020-08-20 15:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0012_auto_20200820_1520'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis_vocabularies', '0007_auto_20200820_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PassageLanguage',
            new_name='PublicationLanguage',
        ),
    ]
